### ISSUE TITLE
signature spoofing is broken

### ISSUE THREAD

**Issue by alphajoza** [Xtended-Pie/msm_xtended_Xtensions#4]
It seems that all roms that are updated to the January 2019 security patch, lost signature spoofing functionality. These roms that I have personally checked include: Havoc-os, Syberia-os, Viper-os, AOSP Extended, Arrow, and MSM Xtended.

**Comment by SuperDroidBond** [comment]
Yes, we are aware about it. Unfortunately haven't found anything yet to fix it.

**Comment by alphajoza** [comment]
https://github.com/Havoc-OS/android_frameworks_base/commit/99c768da7820e0572a9025dabb934ae4505beb77
